### ISSUE TITLE
Manter Milestone

### ISSUE THREAD

**Issue by luizguilherme5** [github-requirements/docs#21]
Eu como **usuário**
Gostaria de criar um sistema milestone
Para que um conjunto de informações sejam melhores rastreadas a partir de um contexto maior.

#### Critérios de Aceitação
- [ ] A milestone deve possuir um título
- [ ] A milestone deve possuir a disponibilidade de inserir uma descrição
- [ ] A milestone deve ter a disponibilidade de inserir um prazo de vencimento para a mesma
- [ ] A milestone deve possuir uma opção para fecha-la
- [ ] A milestone deve possuir uma opção para deleta-la
- [ ] A milestone deve possuir uma opção para edita-la.
- [ ] Deve possuir uma listagem das milestones cadastrada.
